CREATE TABLE pessoa (
	codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(120) NOT NULL,
	ativo BOOLEAN NOT NULL,
	logradouro VARCHAR(120) NULL,
	numero VARCHAR(10) NULL,
	complemento VARCHAR(60) NULL,
	bairro VARCHAR(60) NULL,
	cep VARCHAR(10) NULL,
	cidade VARCHAR(120) NULL,
	estado VARCHAR(2) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;